config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html  
  # Defines the root path route ("/")
  root to: "home#index"

  devise_for :users, controllers: { sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations', }

  resources :employees

  devise_scope :user do
    get 'otp_verification', to: 'users/sessions#otp_verification', as: :otp_verification
    post 'verify_otp', to: 'users/sessions#verify_otp', as: :verify_otp
  end

  resources :tasks

  resources :users do
    resources :tasks do
      member do
        get :mark_completed
        post :upload_document
      end
    end
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  load_and_authorize_resource class: 'User'
  before_action :authenticate_user!
  before_action :set_user, except: [:index, :show, :new, :create]

  def index
    @employees = User.employees
  end

  def new
    @employee = User.new
  end

  def show
    @tasks = current_user.tasks
  end

  def create
    @employee = User.new(employee_params)

    if @employee.save
      redirect_to employees_path, notice: 'Employee created successfully. Default password is `password`,
      employee need to update this later'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @employee.update(employee_params)
      redirect_to employees_path, notice: 'Employee updated successfully. Default password is `password`,
      employee need to update this later'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @employee.destroy
    redirect_to employees_path, notice: 'Employee deleted successfully.'
  end

  private

  def set_user
    @employee = User.find(params[:id])
  end

  def employee_params
    params.require(:user).permit(:name, :email, :department, :onboarding_status)
  end
end

app/views/employees/_form.html.erb
<%= form_with model: @employee, local: true, url: @employee.new_record? ? employees_path : employee_path(@employee) do |form| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation" class="border p-4 rounded text-red-600 border-red-600">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>
      <ul>
        <% @employee.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group my-2">
    <%= form.label :name, class: "form-label block font-bold" %>
    <%= form.text_field :name, class: "form-control w-full rounded mt-1 shadow" %>
  </div>

  <div class="form-group my-4">
    <%= form.label :email, class: "form-label block font-bold" %>
    <%= form.email_field :email, class: "form-control w-full rounded mt-1 shadow" %>
  </div>

  <div class="form-group my-4">
    <%= form.label :department, class: "form-label block font-bold" %>
    <%= form.text_field :department, class: "form-control w-full rounded mt-1 shadow" %>
  </div>

  <div class="form-group my-4">
    <%= form.label :onboarding_status, class: "form-label block font-bold" %>
    <%= form.select :onboarding_status, options_for_select([['Not Started', 'not_started'], ['In Progress', 'in_progress'], ['Completed', 'completed']], @employee.onboarding_status), {}, class: "form-control w-full rounded mt-1 shadow" %>
  </div>

  <div class="form-group my-10">
    <%= form.submit class: "btn btn-primary bg-cyan-600 py-2 text-white w-full rounded font-bold" %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<div class="border rounded-lg my-10 shadow p-10 w-11/10 sm:w-5/12 mx-auto block">
  <h1 class="font-bold text-2xl text-center mb-8">Edit Employee</h1>

  <%= render 'form', employee: @employee %>
  <button class="bg-black text-white rounded">
    <%= link_to 'Back', employees_path, class:'py-2 px-5 inline-block' %>
  </button>
</div>

app/views/employees/index.html.erb
<div class="container mx-auto px-2">
  <div class="flex justify-between my-10 flex-wrap">
    <h1 class="text-4xl font-bold">Employees</h1>
    <div class="mt-3 sm:mt-0">
      <button class="bg-cyan-600 rounded mr-2 text-white font-bold">
        <%= link_to 'Add New Employee', new_employee_path, class:'px-3 py-2 inline-block' %>
      </button>
      <button class="bg-cyan-600 rounded ml-2 text-white font-bold">
        <%= link_to 'Back to Home', root_path, class:'px-3 py-2 inline-block' %>
      </button>
    </div>
  </div>
  <div class="overflow-x-auto w-screen sm:w-full">
    <table class="table-auto w-full my-3">
      <thead>
        <tr>
          <th class="bg-black p-3 text-white text-start rounded-tl-lg">Name</th>
          <th class="bg-black p-3 text-white text-start">Email</th>
          <th class="bg-black p-3 text-white text-start">Department</th>
          <th class="bg-black p-3 text-white text-start">Onboarding Status</th>
          <th class="bg-black p-3 text-white text-start rounded-tr-lg">Actions</th>
        </tr>
      </thead>
      <tbody class="border rounded-br-lg rounded-bl-lg">
        <% @employees.each do |employee| %>
          <tr class="border-b-2">
            <td class="p-3 text-black text-start"><%= employee.name %></td>
            <td class="p-3 text-black text-start"><%= employee.email %></td>
            <td class="p-3 text-black text-start"><%= employee.department %></td>
            <td class="p-3 text-black text-start"><%= employee.onboarding_status %></td>
            <td class="p-3 text-black text-start flex">
              <button class="bg-cyan-600 rounded mr-1 mt-1 text-white">
                <%= link_to 'Edit', edit_employee_path(employee), class: 'px-3 py-2 inline-block' %>
              </button>
              <button class="bg-cyan-600 rounded ml-1 mt-1 text-white">
                <%= link_to 'Delete', employee_path(employee), class: 'px-3 py-2 inline-block', data: { "turbo-method": :delete } %>
              </button>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/employees/new.html.erb
<div class="border rounded-lg my-10 shadow p-10 w-11/12  sm:w-5/12 mx-auto block">
  <h1 class="font-bold text-2xl text-center mb-8">New Employee</h1>

  <%= render 'form', employee: @employee %>

  <button class="bg-black text-white rounded">
    <%= link_to 'Back', employees_path, class:'py-2 px-5 inline-block' %>
  </button>
</div>

app/views/employees/show.html.erb
<div class="container mx-auto px-2">
  <div class="flex justify-between mt-10 flex-wrap mb-4">
    <h1 class="text-4xl font-bold"><%= current_user.name %>'s Profile</h1>
  </div>
  <div class="flex w-full flex-wrap mb-5">
    <div class="w-full sm:w-4/12 border p-2">
      <p><span class="font-bold">Email:</span> <%= current_user.email %></p>
    </div>
    <div class="w-full sm:w-4/12 border p-2">
      <p><span class="font-bold">Department:</span> <%= current_user.department %></p>
    </div>
    <div class="w-full sm:w-4/12 border p-2">
      <p><span class="font-bold">Onboarding Status:</span> <%= current_user.onboarding_status %></p>
    </div>
  </div>

  <h2 class="text-2xl font-bold">Your Tasks</h2>
  <div class="overflow-x-auto w-screen sm:w-full">
      <table class="table-auto w-full my-3">
        <thead>
          <tr>
            <th class="bg-black p-3 text-white text-start rounded-tl-lg">Title</th>
            <th class="bg-black p-3 text-white text-start">Description</th>
            <th class="bg-black p-3 text-white text-start">Status</th>
            <th class="bg-black p-3 text-white text-start">Due Date</th>
            <th class="bg-black p-3 text-white text-start rounded-tr-lg">Actions</th>
          </tr>
        </thead>
        <tbody class="border rounded-br-lg rounded-bl-lg">
          <% @tasks.each do |task| %>
            <tr class="border-b-2">
              <td class="p-3 text-black text-start"><%= task.title %></td>
              <td class="p-3 text-black text-start"><%= task.description %></td>
              <td class="p-3 text-black text-start"><%= task.status %></td>
              <td class="p-3 text-black text-start"><%= task.due_date %></td>
              <td class="p-3 text-black text-start flex">
                <% if task.status == 'pending' %>
                  <button class="bg-cyan-600 rounded mr-1 mt-1 text-white">
                    <%= link_to 'Mark as Completed', mark_completed_user_task_path(current_user, task), class: 'px-3 py-2 inline-block', method: :post %>
                  </button>
                  <%= form_with url: upload_document_user_task_path(current_user, task), local: true, method: :post do |f| %>
                    <%= f.file_field :document, class: "form-control rounded mt-1 border-gray-500 border p-2" %>
                    <%= f.submit 'Upload Document', class: "btn btn-primary bg-cyan-600 py-2 text-white px-3 rounded font-bold" %>
                  <% end %>
                <% else %>
                  <p>Document uploaded</p>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <button class="bg-black text-white rounded">
    <%= link_to 'Back to Home', root_path, class:'py-2 px-5 inline-block' %>
  </button>
</div>