config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html  
  # Defines the root path route ("/")
  root to: "home#index"

  devise_for :users, controllers: { sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations', }

  resources :employees

  devise_scope :user do
    get 'otp_verification', to: 'users/sessions#otp_verification', as: :otp_verification
    post 'verify_otp', to: 'users/sessions#verify_otp', as: :verify_otp
  end

  resources :tasks

  resources :users do
    resources :tasks do
      member do
        get :mark_completed
        post :upload_document
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/views/home/index.html.erb
<nav class="bg-gray-800">
  <div class="container mx-auto px-2 sm:px-6 lg:px-8">
    <div class="relative flex h-16 items-center justify-between">
      <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
        <button type="button" class="relative inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white" aria-controls="mobile-menu" aria-expanded="false">
          <span class="absolute -inset-0.5"></span>
          <span class="sr-only">Open main menu</span>
          <svg class="block h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
          <svg class="hidden h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-between">
        <div class="flex flex-shrink-0 items-center text-white font-bold">
          Logo
        </div>
        <div class="hidden sm:ml-6 sm:block">
          <div class="flex space-x-4">
            <%= link_to 'Update My Profile', edit_user_registration_path, class: 'rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white' %>

            <% if user_signed_in? %>
              <%= link_to "Sign Out", destroy_user_session_path, class: 'rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white', data: { "turbo-method": :delete } %>
            <% end %>
          </div>
        </div>
      </div>
      
    </div>
  </div>

  <div class="sm:hidden" id="mobile-menu">
    <div class="space-y-1 px-2 pb-3 pt-2">
      <%= link_to 'Update My Profile', edit_user_registration_path, class: 'block rounded-md bg-gray-900 px-3 py-2 text-base font-medium text-white' %>
      <% if user_signed_in? %>
        <%= link_to "Sign Out", destroy_user_session_path, class: 'block rounded-md bg-gray-900 px-3 py-2 text-base font-medium text-white', data: { "turbo-method": :delete } %>
      <% end %>
    </div>
  </div>
</nav>

<div class="bg-teal-200 h-screen flex pt-20">
  <div class="container mx-auto flex flex-col items-center w-full">
    <h1 class="text-6xl text-black font-extrabold leading-tight capitalize text-center w-9/12 my-10">Welcome to the Employee Onboarding Portal</h1>
    <div>
      <% if user_signed_in? && current_user.hr? %>
        <button class="bg-cyan-600 px-3 py-2 rounded mr-4">
          <%= link_to "Manage Employees", employees_path, class: "rounded-md px-3 py-2 text-sm font-medium text-white" %>
        </button>
        <button class="bg-cyan-600 px-10 py-2 rounded ml-4">
          <%= link_to 'Task Tracker', tasks_path, class: 'rounded-md px-3 py-2 text-sm font-medium text-white' %>
        </button>
      <% end %>
      <% if user_signed_in? && current_user.employee? %>
        <button class="bg-cyan-600 px-3 py-2 rounded mr-4">
            <%= link_to 'View My Tasks', employee_path(current_user), class: 'rounded-md px-3 py-2 text-sm font-medium text-white' %>
        </button>
      <% end %>
    </div>
  </div>
</div>